name: Build and Update GitOps

on:
  push:
    branches:
      - gitops

permissions:
  contents: write

env:
  AWS_REGION: us-east-2
  ECR_REPOSITORY: hello-flask
  ECR_REGISTRY: 113892881104.dkr.ecr.us-east-2.amazonaws.com
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 113892881104.dkr.ecr.us-east-2.amazonaws.com

      - name: Build and push Docker image
        run: |
          docker build --no-cache -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./app
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Update Helm image tag
        run: |
          sed -i "s/tag: .*/tag: \"$IMAGE_TAG\"/" helm/values.yaml

      - name: Commit and push updated Helm values
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add helm/values.yaml
          git commit -m "Update image tag to $IMAGE_TAG" || echo "No changes to commit"
          git push origin gitops